spring.application.name=resume-analyser-backend

server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/resume_analyser}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Priyanshu@1437}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET:MySuperSecretKeyForResumeAnalyserProject2026MySuperSecretKey}
jwt.expiration=86400000
file.upload-dir=${FILE_UPLOAD_DIR:uploads}
gemini.api.key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent}