spring.application.name=resume-analyser-backend

spring.datasource.url=jdbc:mysql://localhost:3306/resume_analyser
spring.datasource.username=root
spring.datasource.password=Priyanshu@1437

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
jwt.secret=MySuperSecretKeyForResumeAnalyserProject2026MySuperSecretKey
jwt.expiration=86400000